#:kivy 1.10.0
#:include nodelist.kv
#:include editdatapanel.kv
#:include nodesensordisplay.kv

<Controller>:
  id: controller
  orientation: 'horizontal'
  padding: 10
  spacing: 10
  size_hint_x: None
  width: '900dp'
  data_panel: data_panel
  NodeList:
    width: '120dp'
    size_hint_y: 1
    size_hint_x: None
  EditDataPanel:
    id: data_panel
  NodeSensorDisplay:
    id: sensor_disp
    width: '500dp'
    size_hint_y: 1
    size_hint_x: None
